apiVersion: apps/v1
kind: Deployment
metadata:
  name: littleflow
spec:
  template:
    spec:
      containers:
      - name: worker
        args: ["/app/$(ARCHIVE)","-w","2","-b","0.0.0.0:5000","littleflow_redis.service:service"]
        ports:
          - containerPort: 5000
