apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -api

commonLabels:
  app: littleflow
  role: api

bases:
- ../archive-run

resources:
- service.yaml

patches:
- path: api.yaml

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: littleflow
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SHIV_ENTRY_POINT
        value: littleflow_redis.service:main
