apiVersion: v1
kind: Service
metadata:
  name: littleflow
  labels:
    app: littleflow
    role: api
spec:
  selector:
    app: littleflow
    role: api
  clusterIP: None
  ports:
  - name: http
    port: 5000
