apiVersion: apps/v1
kind: Deployment
metadata:
  name: littleflow
  labels:
    app: littleflow
spec:
  selector:
    matchLabels:
      app: littleflow
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: littleflow
    spec:
      serviceAccountName: littleflow
      containers:
      - name: worker
        image: python:3.10
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: password
        - name: REDIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: redis
              key: username
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: redis_host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: config
              key: redis_port
        - name: ARCHIVE
          valueFrom:
            configMapKeyRef:
              name: config
              key: archive
        - name: ISSUER
          value: /etc/issuer/identity.json
        command: ["/app/run.sh"]
        args: ["/app/$(ARCHIVE)", "receipts"]
        volumeMounts:
        - name: app
          mountPath: /app
      volumes:
      - name: app
        emptyDir: {}
