apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {NAMESPACE}
nameSuffix: -{SUFFIX}

bases:
- ../remote-build/base

configMapGenerator:
  - name: config
    env: config.properties

secretGenerator:
- name: storage
  env: storage.properties

patches:
- path: arch.yaml
