apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: build
nameSuffix: -mybuild

bases:
- ../base

configMapGenerator:
  - name: config
    env: config.properties

secretGenerator:
- name: storage
  env: storage.properties
