apiVersion: apps/v1
kind: Deployment
metadata:
  name: littleflow
spec:
  template:
    spec:
      initContainers:
      - name: config
        image: python:3.10
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE
          value: http://littleflow-api.$(NAMESPACE).svc.cluster.local:5000/
        command: ["/bin/bash","-c"]
        args:
        - |-
          set -e;
          export MODULE_DIR=/app/console_config;
          mkdir ${MODULE_DIR};
          echo "class K8sConfig:" >> ${MODULE_DIR}/__init__.py;
          echo "   API='${SERVICE}'" >> ${MODULE_DIR}/__init__.py;
        volumeMounts:
        - name: app
          mountPath: /app
      containers:
      - name: worker
        args: ["/app/$(ARCHIVE)","-w","2","-b","0.0.0.0:8000","littleflow_redis.console:service"]
        ports:
          - containerPort: 8000
