apiVersion: apps/v1
kind: Deployment
metadata:
  name: littleflow
spec:
  template:
    spec:
      initContainers:
        - name: download
          image: python:3.10
          imagePullPolicy: IfNotPresent
          env:
          - name: BUCKET
            valueFrom:
              configMapKeyRef:
                name: config
                key: bucket
          - name: BUCKET_PATH
            valueFrom:
              configMapKeyRef:
                name: config
                key: path
          - name: ARCHIVE
            valueFrom:
              configMapKeyRef:
                name: config
                key: archive
          command: ["/bin/bash","-lc"]
          args:
          - |-
            set -e;
            echo "Downloading s3://${BUCKET}/${BUCKET_PATH}/${ARCHIVE} to /app/${ARCHIVE}";
            pip install boto3;
            python -c "import boto3; s3 = boto3.client('s3'); s3.download_file('${BUCKET}','${BUCKET_PATH}${ARCHIVE}','/app/${ARCHIVE}')";
            echo '#!/bin/bash -l' >> /app/run.sh;
            echo 'cd /app' >> /app/run.sh;
            echo '/usr/local/bin/python $*' >> /app/run.sh;
            chmod +x /app/run.sh
          volumeMounts:
          - name: app
            mountPath: /app
          - name: aws-config
            mountPath: /root/.aws
