apiVersion: apps/v1
kind: Deployment
metadata:
  name: littleflow
spec:
  template:
    spec:
      initContainers:
        - name: download
          image: google/cloud-sdk:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: BUCKET
            valueFrom:
              configMapKeyRef:
                name: config
                key: bucket
          - name: BUCKET_PATH
            valueFrom:
              configMapKeyRef:
                name: config
                key: path
          - name: ARCHIVE
            valueFrom:
              configMapKeyRef:
                name: config
                key: archive
          - name: SOURCE
            value: gs://$(BUCKET)/$(BUCKET_PATH)$(ARCHIVE)
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /etc/issuer/identity.json
          command: ["/bin/bash","-lc"]
          args:
          - |-
            set -e;
            gcloud auth activate-service-account --key-file /etc/issuer/identity.json;
            echo "Downloading ${SOURCE} to /app/${ARCHIVE}";
            gsutil -D cp ${SOURCE} /app/${ARCHIVE};
            echo '#!/bin/bash -l' >> /app/run.sh;
            echo 'cd /app' >> /app/run.sh;
            echo '/usr/local/bin/python $*' >> /app/run.sh;
            chmod +x /app/run.sh
          volumeMounts:
          - name: app
            mountPath: /app
          - name: issuer
            mountPath: /etc/issuer
            readOnly: true
      volumes:
      - name: app
        emptyDir: {}
      - name: issuer
        secret:
          secretName: issuer
