apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: littleflow

configMapGenerator:
  - name: config
    env: config.properties

secretGenerator:
- name: redis
  env: redis.properties
